# Generated by Django 2.2.7 on 2021-01-25 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0003_auto_20210125_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
