# Generated by Django 2.2.7 on 2021-01-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0004_answer_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='update_date',
            field=models.DateTimeField(),
        ),
    ]
