# Generated by Django 2.2.7 on 2021-01-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpoll', '0005_auto_20210125_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='update_date',
        ),
    ]
